apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azurewest
  tags:
    - azure
    - demo
    - datalake
  description: This is resource provider azurewest for azure cloud
spec:
  type: resourceprovidertype
  system: Demo
  lifecycle: experimental
  owner: Demo