
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: westazure
  tags:
    - azure
    - hod
    - provider
  description: This is resource provider for azure
  annotations:
    github.com/project-slug: 'https://github.com/hiteshshrivastava/demo-tenant-metadata'
    backstage.io/techdocs-ref: dir:.
spec:
  type: resource_provider
  system: DEMO
  lifecycle: experimental
  owner: DEMO
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demotenant
  tags:
    - azure
    - demo
    - tenant
  description: This is tenant 'demotenant'' resource provider 'westazure'
  annotations:
    github.com/project-slug: 'https://github.com/hiteshshrivastava/demo-tenant-metadata'
    backstage.io/techdocs-ref: dir:.
spec:
  type: tenant
  system: DEMO
  lifecycle: experimental
  owner: DEMO
  dependsOn: [component:westazure]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tenantdemo
  tags:
    - azure
    - demo
    - compute
  description: This is 'tenantdemo' of type 'compute' tenant 'demotenant' resource provider 'westazure'
  annotations:
    github.com/project-slug: 'https://github.com/hiteshshrivastava/demo-tenant-metadata'
    backstage.io/techdocs-ref: dir:.
spec:
  type: resource_entity
  system: DEMO
  lifecycle: experimental
  owner: DEMO
  dependsOn: [component:demotenant]
