apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jknjnnjkn
  annotations:
    backstage.io/techdocs-ref: value
  tags:
    - azure
    - demo
    - datalake
  description: This is resource provider jknjnnjkn for azure cloud
spec:
  type: resourceprovidertype
  system: Demo
  lifecycle: experimental
  owner: Demo

